### ISSUE TITLE
UI Update/CleanUp for GSoC18

### ISSUE THREAD

**Issue by ExactlyMay** [systers/communities#73]
## Description
As a developer,
I need to complete the branding of the app,
so that I can push a final product to production.

## Mocks
![0001](https://user-images.githubusercontent.com/2440938/43679434-3db49e54-97f3-11e8-801c-f2bc8de93abc.jpg)
-
![0003](https://user-images.githubusercontent.com/2440938/43679436-3dca8c82-97f3-11e8-87ff-d168a79f06af.jpg)
-
![0002](https://user-images.githubusercontent.com/2440938/43679435-3dc05d84-97f3-11e8-84ed-d90dc22bf1fc.jpg)
-
![0004](https://user-images.githubusercontent.com/2440938/43679437-3dd60864-97f3-11e8-8cf5-7f4a176f5646.jpg)
-
![0005](https://user-images.githubusercontent.com/2440938/43679438-3de2a95c-97f3-11e8-9618-947f485adbb2.jpg)
-

### Update [Required]
- [90%] Navbar updated to white buttons on the top right, with blue on hover, and underline on active.
- [ ] Footer updated to three links on the right: [Code of Conduct](https://ghc.anitab.org/code-of-conduct/), [Terms & Conditions](https://anitab.org/terms-of-use/), and [Privacy Policy](https://anitab.org/privacy-policy/)
- [ ] Footer remove "Contact Us" and the "We connect" statement.
- [ ] Remove blue footer and update to 
![image](https://user-images.githubusercontent.com/2440938/43738297-114c1c98-9992-11e8-86bf-a0d16425836b.png)

- [ ] Headers updated to ---
- [ ] Sub-headers updated to ---
- [ ] Text updated to ---
- [ ] Buttons updated to ---

- [ ] Update favicon to [32x32 png](https://anitab.org/wp-content/assets/images/favicons/favicon-32x32.png) on desktop, [16x16 png](https://anitab.org/wp-content/assets/images/favicons/favicon-16x16.png) on mobile/tablet.

### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours
